version: '3.1'

services:
  mongodb:
    image: mongo
    env_file:
      - ../../.env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
