version: '3.1'

services:
  mongodb:
    image: mongo
    env_file:
      - ../../.env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: 'rabbitmq-basket'
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge